-- ==================================================================
-- 실습용 스키마.  seed/10-seed.sql 앞에 붙여서 실행됩니다 (make seed-small / seed-large)
--
-- 의도적으로:
--   * PK 외 인덱스는 만들지 않습니다 (01-index-explain 에서 직접 설계)
--   * FK 제약도 걸지 않습니다 (대량 시드 속도 + 조인 실습에서 플래너가 FK 에 기대지 않게)
--   * PK 도 데이터를 넣은 뒤에 붙입니다 (10-seed.sql 끝부분). 인덱스를 유지하면서 INSERT 하는 것보다 훨씬 빠릅니다.
-- ==================================================================
\set ON_ERROR_STOP on

DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY,
  email         text        NOT NULL,
  name          text        NOT NULL,
  country       char(2)     NOT NULL,   -- KR 편중
  tier          text        NOT NULL,   -- free 85% / pro 12% / enterprise 3%
  created_at    timestamptz NOT NULL,   -- 최근 2년
  last_login_at timestamptz             -- 약 30% NULL
);

CREATE TABLE products (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  sku        text          NOT NULL,
  name       text          NOT NULL,
  category   text          NOT NULL,    -- 10개 카테고리
  price      numeric(10,2) NOT NULL,
  stock      int           NOT NULL,    -- 04-locks 재고 차감 실습용
  created_at timestamptz   NOT NULL
);

CREATE TABLE orders (
  id           bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id      bigint        NOT NULL,  -- 편향: 소수 유저(작은 id)에 주문 집중
  status       text          NOT NULL,  -- completed 70 / shipped 15 / pending 10 / cancelled 4.9 / refunded 0.09 / disputed 0.01 (%)
  total_amount numeric(12,2) NOT NULL,
  coupon_code  text,                    -- 약 90% NULL
  memo         text,                    -- 약 70% NULL, 나머지는 문장 + ref 코드 (LIKE 실습용)
  created_at   timestamptz   NOT NULL,  -- 최근 1년
  shipped_at   timestamptz             -- shipped/completed 만 값 있음
);

CREATE TABLE order_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY,
  order_id   bigint        NOT NULL,
  product_id bigint        NOT NULL,    -- 인기 상품 편중
  quantity   int           NOT NULL,    -- 대부분 1
  unit_price numeric(10,2) NOT NULL
);
